apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: postopia
spec:
  selector:
    matchLabels:
      app: search-service
  replicas: 1
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: postopia-search:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
            - name: spring.cloud.nacos.discovery.server-addr
              value: "nacos:8848"
            - name: spring.cloud.nacos.config.server-addr
              value: "nacos:8848"
            - name: spring.elasticsearch.uris
              value: "http://elasticsearch:9200"
            - name: spring.kafka.bootstrap-servers
              value: "kafka:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: postopia
spec:
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: search-service