services:
  # app:
  #   image: 'docker-spring-boot-postgres:latest'
  #   build:
  #     context: .
  #   container_name: postopia-app
  #   depends_on:
  #     - postgres
  #   environment:
  #     - POSTGRES_USER=postopia_dev
  #     - POSTGRES_PASSWORD=postopia_dev
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postopia_dev
  #     - SPRING_DATASOURCE_USERNAME=postopia_dev
  #     - SPRING_DATASOURCE_PASSWORD=postopia_dev
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #   ports:
  #     - "8080:8080"

  postgres:
    image: 'postgres:latest'
    container_name: postopia-db
    environment:
      - POSTGRES_DB=postopia_dev
      - POSTGRES_PASSWORD=postopia_dev
      - POSTGRES_USER=postopia_dev
    ports:
      - "5432:5432"
  redis:
    # 与 ’redis:latest' subtle differences
    image: redis:latest
    container_name: postopia-redis
    ports:
      - "6379:6379"