version: '3.8'
services:
  # service-registry
  mysql:
    build:
        context: ./server-registry
        dockerfile: Dockerfile
    image: postopia-nacos-mysql
    container_name: nacos-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=nacos_config
      - MYSQL_PASSWORD=nacos_config
      - MYSQL_DATABASE=nacos_config  # 数据库初始化[5](@ref)
      - LANG=C.UTF-8
    volumes:
      - mysql_volume:/var/lib/mysql  # 数据持久化[1](@ref)
    ports:
      - "3306:3306"
    healthcheck: # 健康检查确保依赖顺序[1](@ref)
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 3
  nacos:
    depends_on:
      mysql:
        condition: service_healthy  # 等待 MySQL 就绪[1](@ref)
    image: nacos/nacos-server:v2.4.0
    container_name: postopia-nacos
    ports:
      - "8848:8848"  # 控制台端口
      - "9848:9848"  # gRPC通信端口[6](@ref)
    environment:
      - MYSQL_SERVICE_PORT=3306
      - MODE=standalone  # 单机模式[3,4](@ref)
      - PREFER_HOST_MODE=hostname  # 使用主机名标识[6](@ref)
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - NACOS_AUTH_ENABLE=false
      - MYSQL_SERVICE_HOST=mysql  # 使用服务名通信[2](@ref)
      - MYSQL_SERVICE_USER=nacos_config
      - MYSQL_SERVICE_PASSWORD=nacos_config
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    volumes:
      - nacos_volume:/home/nacos/logs
      - nacos_data_volume:/home/nacos/data
    restart: always

  # redis
  redis:
    image: redis:latest
    container_name: postopia-redis
    ports:
      - "6379:6379"

  # kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: postopia-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: postopia-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # elasticsearch
  elasticsearch:
    build:
      context: ./elastic-search
      dockerfile: Dockerfile
    image: postopia-es
    container_name: postopia-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  # user-service
  user-postgres:
    image: 'postgres:latest'
    container_name: user-db
    environment:
      - POSTGRES_DB=postopia_user
      - POSTGRES_PASSWORD=postopia_user
      - POSTGRES_USER=postopia_user
    ports:
      - "54321:5432"

  # space-service
  space-postgres:
    image: 'postgres:latest'
    container_name: space-db
    environment:
      - POSTGRES_DB=postopia_space
      - POSTGRES_PASSWORD=postopia_space
      - POSTGRES_USER=postopia_space
    ports:
      - "54322:5432"

  # post-service
  post-postgres:
    image: 'postgres:latest'
    container_name: post-db
    environment:
      - POSTGRES_DB=postopia_post
      - POSTGRES_PASSWORD=postopia_post
      - POSTGRES_USER=postopia_post
    ports:
      - "54323:5432"

  # comment-service
  comment-postgres:
    image: 'postgres:latest'
    container_name: comment-db
    environment:
      - POSTGRES_DB=postopia_comment
      - POSTGRES_PASSWORD=postopia_comment
      - POSTGRES_USER=postopia_comment
    ports:
      - "54324:5432"

  # message-service
  message-postgres:
    image: 'postgres:latest'
    container_name: message-db
    environment:
      - POSTGRES_DB=postopia_message
      - POSTGRES_PASSWORD=postopia_message
      - POSTGRES_USER=postopia_message
    ports:
      - "54325:5432"

  # vote-service
  vote-postgres:
    image: 'postgres:latest'
    container_name: vote-db
    environment:
      - POSTGRES_DB=postopia_vote
      - POSTGRES_PASSWORD=postopia_vote
      - POSTGRES_USER=postopia_vote
    ports:
      - "54326:5432"

  # opinion-service
  opinion-postgres:
    image: 'postgres:latest'
    container_name: opinion-db
    environment:
      - POSTGRES_DB=postopia_opinion
      - POSTGRES_PASSWORD=postopia_opinion
      - POSTGRES_USER=postopia_opinion
    ports:
      - "54327:5432"

volumes:
  nacos_volume:
  mysql_volume:
  nacos_data_volume: