spring:
  kafka:
    producer:
      batch-size: 16384
      compression-type: snappy
      retries: 3
      bootstrap-servers: localhost:9092
      properties:
        linger.ms: 1000
    consumer:
      group-id: consumer-group
      max-poll-records: 1000
      fetch-min-size: 10240
      fetch-max-wait: 1000
      bootstrap-servers: localhost:9092

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: postopia

  # 默认连接池配置（HikariCP）[3,4](@ref)
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/postopia_dev?rewriteBatchedStatements=true
    username: postopia_dev
    password: postopia_dev

  # JPA 配置

  jpa:
    hibernate:
      ddl-auto: update  # 测试环境设为 update，生产环境应为 none[1](@ref)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
          order_inserts: true
          batch_versioned_data: true
        generate_statistics: true
    show-sql: true



  # 邮件配置
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 64  # 最大连接数
          min-idle: 5     # 最小空闲连接
          max-wait: 100ms # 等待超时

# 自定义 JWT 配置
postopia:
  vote:
    comment:
      threshold: 1
      duration: 1
    post:
      threshold: 1
      duration: 1
    space:
      threshold: 1
      duration: 1

  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    refresh-token:
      expiration: 2592000000
    issuer: postopia.heslin

  # 邮件模板配置
  mail:
    from: noreply@postopia.com
    auth:
      subject: Email Address Authentication

  # 云服务配置
  os:
    apikey: ${CLOUDINARY_URL}

  # 头像 URL 配置
  avatar:
    space: https://res.cloudinary.com/dz2tishzo/image/upload/v1744035577/2025-conference-cat_yylqqz.jpg
    user: https://res.cloudinary.com/dz2tishzo/image/upload/v1742789232/user_avatar/6510615555426900569.png

  # 开放 API 路径（列表配置）[1](@ref)
  open:
    apis: path1, path2

server:
  port: 8081