spring:
  application:
    name: postopia

  # 默认连接池配置（HikariCP）[3,4](@ref)
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/postopia_dev
    username: postopia_dev
    password: postopia_dev

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 测试环境设为 update，生产环境应为 none[1](@ref)

  # 邮件配置
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379

# 自定义 JWT 配置
postopia:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    refresh-token:
      expiration: 2592000000
    issuer: postopia.heslin

  # 邮件模板配置
  mail:
    from: noreply@postopia.com
    auth:
      subject: Email Address Authentication

  # 云服务配置
  os:
    apikey: ${CLOUDINARY_URL}

  # 头像 URL 配置
  avatar:
    space: https://res.cloudinary.com/dz2tishzo/image/upload/v1727686154/73648326_mygdb6.jpg
    user: https://res.cloudinary.com/dz2tishzo/image/upload/v1727686154/73648326_mygdb6.jpg

  # 开放 API 路径（列表配置）[1](@ref)
  open:
    apis: path1, path2

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        core:
          convert: DEBUG