name: Server Custom Task
on:
  push:
    branches: [main]  # 触发条件：推送至 main 分支
  workflow_dispatch:   # 支持手动触发

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码

      - name: Add server host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 47.97.225.160 >> ~/.ssh/known_hosts  # 替换 your_server_ip
          chmod 600 ~/.ssh/known_hosts
          
      - name: Test Secret Access
        run: |
          if [ -n "${{ secrets.SERVER_SSH_KEY }}" ]; then
            echo "Secret exists! First 3 chars: ${SECRET:0:3}​**​*"
          else
            echo "Secret NOT FOUND!"
          fi
        env:
          SECRET: ${{ secrets.SERVER_SSH_KEY }}

      - name: SSH Connection
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > deploy_key  # 移除多余符号
          chmod 600 deploy_key  # 设置密钥权限
          ssh -i deploy_key root@47.97.225.160 "/root/starter.sh"
        env:
          SECRET: ${{ secrets.SERVER_SSH_KEY }}
        
