name: Server Custom Task
on:
  push:
    branches: [main]  # 触发条件：推送至 main 分支
  workflow_dispatch:   # 支持手动触发

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 检出代码

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem  # 设置密钥权限

      - name: Run Remote Commands
        uses: appleboy/ssh-action@master  # SSH 执行命令
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: deploy_key.pem
          script: |  # 自定义操作示例
            cd /root/Postopia
            git pull origin main
            ./gradlew clean build
            docker-compose down
            docker build -t postopia-gateway:latest ./gateway
            docker build -t postopia-user:latest ./user-service
            docker build -t postopia-space:latest ./space-service
            docker build -t postopia-post:latest ./post-service
            docker build -t postopia-comment:latest ./comment-service
            docker build -t postopia-message:latest ./message-service
            docker build -t postopia-vote:latest ./vote-service
            docker build -t postopia-opinion:latest ./opinion-service
            docker build -t postopia-search:latest ./search-service
            docker-compose up -d
